from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'fstart{CMD_INDEX}'
        self.MirrorCommand = f'fmirror{CMD_INDEX}'
        self.UnzipMirrorCommand = f'funzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'fzipmirror{CMD_INDEX}'
        self.CancelMirror = f'fcancel{CMD_INDEX}'
        self.CancelAllCommand = f'fcancelall{CMD_INDEX}'
        self.ListCommand = f'flist{CMD_INDEX}'
        self.SearchCommand = f'fsearch{CMD_INDEX}'
        self.StatusCommand = f'fstatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'fusers{CMD_INDEX}'
        self.AuthorizeCommand = f'fauthorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'funauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'faddsudo{CMD_INDEX}'
        self.RmSudoCommand = f'frmsudo{CMD_INDEX}'
        self.PingCommand = f'fping{CMD_INDEX}'
        self.RestartCommand = f'frestart{CMD_INDEX}'
        self.StatsCommand = f'fstats{CMD_INDEX}'
        self.HelpCommand = f'fhelp{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.SpeedCommand = f'fspeedtest{CMD_INDEX}'
        self.CloneCommand = f'fclone{CMD_INDEX}'
        self.CountCommand = f'fcount{CMD_INDEX}'
        self.WatchCommand = f'fwatch{CMD_INDEX}'
        self.ZipWatchCommand = f'fzipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'fqbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'fqbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'fqbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'fleech{CMD_INDEX}'
        self.UnzipLeechCommand = f'funzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'fzipleech{CMD_INDEX}'
        self.QbLeechCommand = f'fqbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'fqbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'fqbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'fleechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'fleechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'

BotCommands = _BotCommands()
